Add missing int conversion
The following error would occur because Python 3 defaults to float
division:

TypeError: %x format: an integer is required, not float